spring.application.name=ecom
# DB Settings
spring.datasource.url=jdbc:mysql://localhost:3306/springbootdb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Hari@2004



#hibernate Settings
spring.jpa.hibernate.ddl-auto=update